# [[file:sbfiles.note::*cargo][cargo:1]]
[package]
name = "sbfiles"
version = "0.0.4"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
structopt = "0.3"
gut = {version="0.1.3", package="gchemol-gut"}
flate2 = "1"
tar = "0.4"
base64 = "0.13"

[dev-dependencies]
duct = "0.13"
tempfile = "3"

# [dependencies.copypasta-ext]
# version = "0.3"
# default-features = false
# features = ["osc52"]
# cargo:1 ends here
