# cargo

# [[file:~/Workspace/Programming/cmdline-tools/sbfiles/sbfiles.note::*cargo][cargo:1]]
[package]
name = "sbfiles"
version = "0.0.3"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
structopt = "0.2"
quicli = "0.4"
flate2 = "1"
tar = "0.4"
base64 = "0.10"

[dev-dependencies]
duct = "0.12"
tempfile = "3"
# cargo:1 ends here
