# cargo

# [[file:~/Workspace/Programming/cmdline-tools/sbfiles/sbfiles.note::*cargo][cargo:1]]
[package]
name = "sbfiles"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
structopt = "0.2"
quicli = "0.4"
zip = "0.5"
duct = "0.12"

[dev-dependencies]
tempfile = "3"
# cargo:1 ends here
